# Generated by Django 3.2.8 on 2021-10-26 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='characteristic',
            name='animals',
            field=models.ManyToManyField(related_name='characteristics', to='animal.Animal'),
        ),
    ]
