# Generated by Django 3.2.8 on 2021-10-26 22:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('animal', '0002_characteristic_animals'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='animal',
        ),
        migrations.AddField(
            model_name='animal',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animal.group'),
        ),
    ]
